version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test: crypto31 # this can be any name you choose
  executor: node/default
  steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Build app


workflows:
  build_test_deploy: crypto31 # this can be any name you choose
  jobs:
      - build_and_test